baseURL = 'https://slides.alextldr.com/'
languageCode = 'en-us'
title = 'AlexTLDR Presentations'
theme = ["github.com/joshed-io/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "dracula"
tabWidth = 2

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
[params.logo]
src = "./img/stuttgart_gophers.png"
alt = "Stuttgart Gophers Logo"
width = "150px"

[params.reveal_hugo]
custom_css = "css/custom.css"
slide_number = true
center = false
controls = true
hash = true
height = "100%"
margin = 0
width = "100%"
highlight_theme = "dracula"

[caches]
[caches.images]
dir = ':cacheDir/images'
